name: Archive Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive repository
      run: tar -czvf code_archive.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: archive
        path: code_archive.tar.gz